apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: package-tracker-ingress
spec:
  rules:
  - host: packagetracker.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: api-service
            port:
              number: 80
